### ISSUE TITLE
Can't send transaction to newly created account (social-recovery tutorial)

### ISSUE THREAD

**Issue by kplusq** [LiskHQ/lisk-sdk-examples#113]
## Expected behavior
when stateStore.account.getOrDefault is called, the default value should be set correctly.

## Actual behavior
Transaction fails with  ```ERROR lisk-framework: Cannot read property 'config' of undefined (module=lisk:app)
Message: Cannot read property 'config' of undefined ``` 
I suppose this is because the default value is not set on SRSAccountSchema

## Steps to reproduce
- create new account
- send token to the new account

**Comment by Tschakki** [comment]
Can you please share the concrete example how you create the account? I don't think this is part of the tutorial. Thanks :)

**Comment by kplusq** [comment]
I just wanted to create new friends list. so I created new account like this.
```
import { Mnemonic } from '@liskhq/lisk-passphrase';
import {
	getAddressFromPassphrase,
	getBase32AddressFromPassphrase,
} from '@liskhq/lisk-cryptography';

const pass = Mnemonic.generateMnemonic();
const binaryAddress = getAddressFromPassphrase(pass).toString('hex');
const lskAddress = getBase32AddressFromPassphrase(pass);
```
since these new accounts don`t have enought token to vouch, I send token to the accounts.
And the error occurred.

**Comment by kplusq** [comment]
I think `accountSchema` is very important for creating customModules, and setting the default value is necessary.
SRSAccountSchema doesn't have the default value, so that causes the error.
https://github.com/LiskHQ/lisk-sdk-examples/blob/5736ec1fbe16f03c9ca8804c14f3bcd50b0db8b3/tutorials/social-recovery/blockchain_app/srs_module/schemas.js#L1

**Comment by Tschakki** [comment]
Hey!
I was able to reproduce the error.

You are right, setting default values in the  account schema seems to solve it. 
I will open a PR to fix it 👍
