### ISSUE TITLE
invoiceCount isn't incremented

### ISSUE THREAD

**Issue by kplusq** [LiskHQ/lisk-sdk-examples#20]
### Expected behavior
`invoice count` should be increased in `applyAsset`.

### Actual behavior
`invoice count` isn't incremented.

### Steps to reproduce
https://github.com/LiskHQ/lisk-sdk-examples/blob/64cf597bbc08e96ec568f527e46901a0cfb7d449/invoice/transactions/invoice_transaction.js#L62

This is a issue about position of Increment Operator.
FROM
sender.asset.invoiceCount = sender.asset.invoiceCount++;
TO
sender.asset.invoiceCount = ++sender.asset.invoiceCount;

also the same applies to decrement logic in `undoAsset`

**Comment by lsilvs** [comment]
Hi @kplusq, thank you for reporting the issue.

You're right. Feel free to open a PR with the fix otherwise we will fix it in the upcoming days ;)
