### ISSUE TITLE
errors should be concatenated with the result of super.applyAsset()

### ISSUE THREAD

**Issue by kplusq** [LiskHQ/lisk-sdk-examples#22]
In applyAsset method like below, `super.applyAsset()` may returns errors.

https://github.com/LiskHQ/lisk-sdk-examples/blob/269061ec26f8b530cdc55a553bf3f99907e5fe08/cashback/cashback_transaction.js#L18
https://github.com/LiskHQ/lisk-sdk-examples/blob/269061ec26f8b530cdc55a553bf3f99907e5fe08/invoice/transactions/payment_transaction.js#L18

so when using `super.applyAsset()`, the result of parent's applyAsset should be used or concat.
if not, it may cause serious security issue.

**Comment by kplusq** [comment]
with those samples, you can increase your balance unlimitedly since negative balance are allowed.
is this in the specifications?

**Comment by lsilvs** [comment]
Yeah, it should be `const errors = super.applyAsset(store);` instead :)

**Comment by kplusq** [comment]
thanks for the response. 
I found this issue when watching https://www.youtube.com/watch?v=wYiM5p6KjDU&t=600s.
so I'm just wandering if materials for tomorrow's webinar will be corrected.

**Comment by RachBLondon** [comment]
We will try, but since the SDK is quite early, it might be a bit of a squeeze.

**Comment by lsilvs** [comment]
Hey @kplusq, I appreciate your concern and commitment.
I've just opened the PR to fix it ;)
https://github.com/LiskHQ/lisk-sdk-examples/pull/25

**Comment by RachBLondon** [comment]
We should open this issue again and revert PR #25 - this fix sends twice the value of the cashback solution than it should. @lsilvs @shuse2

**Comment by RachBLondon** [comment]
Ignore this - my mistake
