### ISSUE TITLE
Invoice client logout doesn't clean up properly

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-sdk-examples#32]
## Current behavior
If you log in with 2 different accounts, then the app seems to jump between them approx. every 5 seconds

![invoice-bug 2019-08-19 12_29_49](https://user-images.githubusercontent.com/1254342/63258794-1de8b000-c27d-11e9-8e39-79aa235625d1.gif)

## Expected behavior
Logout should clean the account properly

**Comment by Tschakki** [comment]
The cashback tutorial will be archived and therefore doesn't need further enhancements.
