### ISSUE TITLE
Docker instructions are wrong/incomplete for transport example

### ISSUE THREAD

**Issue by sudoaza** [LiskHQ/lisk-sdk-examples#45]
## Issue

Failure to run node following the [docker instructions on Linux for the transport example](https://github.com/LiskHQ/lisk-sdk-examples/blob/lisk-transport/transport/DOCKER.md)

## Steps to reproduce

Everything goes great until the `Verify Running Node` step. There `node_modules` are not installed by default as says in the doc. simply running `npm i` inside `/node` folder fails probably for some permission issue. (Maybe related to [#43](https://github.com/LiskHQ/lisk-sdk-examples/issues/43)
) Remove the `node/node_modules` if was created and create a new one with the current user. After that `npm i` succeeds.

```
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm WARN tar ENOENT: no such file or directory, lstat '/home/node/node/node_modules/.staging/faker-ea18f17f/build/build'

```

Even so, trying to run the node fails again missing list-transport dependency. This gets fixed by running `npm i` inside the `/transport` folder. After installing dependencies inside transport going back to /node and running the node succeeds. 

```
LISK-SDK-ENV - node@14514423d05f ~/node $ node index.js | npx bunyan -o short
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@liskhq/lisk-transactions'
```

## Expected behaviour

Either the `docker build` installs the packages (including the transport dependency) or instructions specify the need for `npm i`. Also the install should install all dependencies.

**Comment by michielmulders** [comment]
Hi @sudoaza 
Thanks for your report!

1. First of all, can you provide us information about the operating system you are using?
2. Besides that, would you like to check if you have checked out the right branch? We are using `lisk-transport` for this.

We have spotted a mistake in our flow of the documentation. We don't repeat you should clone the repository locally BUT also checkout the `lisk-transport` branch. I've updated the documentation with instructions on how to do it in the `DOCKER.md`.

Using the `lisk-transport` branch, `node_modules` will be cached, so no need for `npm i`. Let me know if solves the issue for you?

Thanks!

**Comment by sudoaza** [comment]
Hi @michielmulders 

1. I'm using Antergos/Archlinux
2. first i cloned it in the default branch and then checked out `list-transport`, otherwise i didnt have the transport folder. 

I'll retry tonight. How is the `node_modules` cached? Because [its not in the repo](https://github.com/LiskHQ/lisk-sdk-examples/tree/lisk-transport/transport/node) is it done by the `docker build ...` ?

**Comment by michielmulders** [comment]
Hi @sudoaza 

We've checked the Docker script and indeed the `npm i` step is missing for both folders.
We have added it as a separate step for the Docker installation.

Thanks for pointing this out!
Looking forward to meeting you at the event! :)
